---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ops.kubetriage.dev
  resources:
  - incidentpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ops.kubetriage.dev
  resources:
  - incidentpolicies/status
  - incidentreports/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ops.kubetriage.dev
  resources:
  - incidentreports
  verbs:
  - create
  - get
  - list
  - watch
